#!/bin/bash

# change this to your plugin file name
plugin_file_name="plugin.php"

# Get the current version from the plugin file
current_patch_version=$(grep -oP "Version: \K.*" $plugin_file_name | sed 's/.*\.//')

# Increment the last digit of the version
new_patch_version=$(expr "$current_patch_version" + 1)

# ex 2.0.0
old_full_version=$(grep -oP "Version: \K.*" $plugin_file_name)

# Concatenate the old version with the new patch version to form the new full version
new_full_version="${old_full_version%.*}.$new_patch_version"


# Replace the version in the plugin file and create a temporary file
sed -i "s/\(Version:[[:space:]]*\)$old_full_version/\1$new_full_version/" $plugin_file_name

# Get the latest full version from the plugin file
full_version=$(grep -oP "Version: \K.*" $plugin_file_name)

# Replace the version in the package.json
sed -i "s/\"version\": \"[0-9]\+\.[0-9]\+\.[0-9]\+\",/\"version\": \"$full_version\",/" package.json

# Stage the modified plugin file for commit
git add $plugin_file_name package.json


exit 0
